services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - myNetwork
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - myNetwork
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s
  wordpress:
    depends_on:
      mariadb:
        condititon: service_healthy
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/html
    networks:
      - myNetwork

networks:
  myNetwork:
volumes:
  mariadb:
    driver_opts:
      device: /home/rarnold/data/mariadb
      type: none
      o: bind
  wordpress:
    driver_opts:
      device: /home/rarnold/data/wordpress
      type: none
      o: bind
