services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: /home/rarnold/data/wordpress
        target: /var/www/html/
    networks:
      - myNetwork
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - 3306
    env_file:
      - .env
    volumes: /home/rarnold/data/mariadb:/var/lib/mysql
    networks:
      - myNetwork
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - type: bind
        source: /home/rarnold/data/wordpress
        target: /var/www/html
    networks:
      - myNetwork

networks:
  myNetwork:
volumes:
  mariadb:
  wordpress:
